# Site settings
title: Algorithms Visualized
email: jeeyoungk@gmail.com
description: "Visualizing algorithms that I think are cool."
baseurl: "/visualization"
url: "http://jeeyoungk.github.io/visualization"
twitter_username: jeeyoungk
github_username:  jeeyoungk

# Build settings
markdown: kramdown
permalink: pretty
